when:
  branch: main

variables:
  - &file Dockerfile
  - &repo ${DOCKER_BKSOL_USER}/test-woodpecker

steps:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/i386
      dry_run: true
      repo: *repo
      tags: latest
#    when:
#      event: pull_request
#      path: *file

  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/i386
      repo: *repo
      tags: latest
      username: 
        from_secret: DOCKER_BKSOL_USER
      password:
        from_secret: DOCKER_BKSOL_PASS
#    when:
#      event: push
#      path: *file
