when:
  branch: main

variables:
  - &file Dockerfile
  - &repo bksolutions/test-woodpecker


steps:

  prepare:
    image: debian
    commands:
      - echo "This is the build step"
      - "ls -la"
      
  dryrun:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/i386
      dry_run: true
      repo: *repo
      tags: latest
      logins:
        # Default DockerHub login
        - registry: https://index.docker.io/v1/
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS
