when:
  branch: main

variables:
  - &file Dockerfile
  - &repo github.com/${CI_REPO_OWNER}/test-woodpecker

steps:
  dryrun:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/i386
      dry_run: true
      repo: *repo
      tags: latest
#    when:
#      event: pull_request
#      path: *file

#  publish:
#    image: woodpeckerci/plugin-docker-buildx
#    settings:
#      dockerfile: *file
#      platforms: linux/arm/v7,linux/arm64/v8,linux/amd64,linux/ppc64le
#      repo: *repo
#      registry: codeberg.org
#      tags: latest
#      username: ${CI_REPO_OWNER}
#      password:
#        from_secret: cb_token
#    when:
#      event: push
#      path: *file
