---
steps:
  check_files:
    group: info
    image: woodpeckerci/plugin-git
    commands:
      - ls -la
      - ls -la ./.woodpecker
      
  codecov:
    group: info
    image: woodpeckerci/plugin-codecov
    settings:
      files:
        - my-coverage-report-output.out
        - another-coverage-report.json
      token:
        from_secret: codecov_token
      
  prettier:
    group: info
    image: woodpeckerci/plugin-prettier:next
    commands:
      - prettier --check --parser=markdown README.md
      - prettier --write --parser=markdown README.md
      
  trivy:
    group: info
    image: woodpeckerci/plugin-trivy
    settings:
      skip-dirs: ".woodpecker"
      dir: "."
      severity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
