---
variables:
  - &file Dockerfile
  - &dhub https://index.docker.io/v1/
  - &arch linux/amd64
  - &repo bksolutions/CI-CDS

steps:
  build_n_push:
    when:
      - event: [push, manual]
        branch: main
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: *arch
      dry_run: true
      repo: *repo
      tags: 
        - 'latest'
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS
