---
variables:
  - &file Dockerfile
  - &dhub https://index.docker.io/v1/
  - &arch linux/amd64
  - &repo bksolutions/CI-CDS

steps:
  git-clone-ci:
    when:
      - event: [push, manual]
        branch: main
    image: alpine/git
    volumes:
      - ${CI_WORKSPACE}:/git
    commands:
      - ls -la
      - git clone https://forge.codesys.com/git/tol,codesys-4-linux,docker.git/ ci
      - tree ci
        
  build_n_push:
    when:
      - event: [push, manual]
        branch: main
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: ci/codesys-ide/Dockerfile
      platforms: *arch
      dry_run: true
      repo: *repo
      tags: 
        - 'latest'
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS
