---
variables:
  - &file Dockerfile
  - &dhub https://index.docker.io/v1/
  - &arch linux/amd64
  - &repo bksolutions/CI-CDS

steps:
  git-clone-ci:
    when:
      - event: [push, manual]
        branch: main
    image: woodpeckerci/plugin-git
    settings:
      remote: "https://forge.codesys.com/git/tol,codesys-4-linux,docker.git"
      depth: 1
      lfs: false

  verify:
    when:
      - event: [push, manual]
        branch: main
    image: alpine
    commands:
      - ls -la
        
  build_n_push:
    when:
      - event: [manual]
        branch: main
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: *arch
      dry_run: true
      repo: *repo
      tags: 
        - 'latest'
      registry: *dhub
      logins:
        - registry: *dhub
          username:
            from_secret: DOCKER_BKSOL_USER
          password:
            from_secret: DOCKER_BKSOL_PASS
